---
- name: Importation de la clé public nodejs
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Ajout du repo node js
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{node_version}}.x {{ ansible_distribution_release }} main'
    state: present

- name: Installation de nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install pm2 package globally.
  npm:
    name: pm2
    global: yes
