Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  # server_1 VM
  config.vm.define "server_1" do |server_1|
    server_1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "server_1"
    end
    server_1.vm.network "private_network", ip: "192.168.33.22"
    server_1.vm.hostname = "server_1"
  end

  # server_2 VM
  config.vm.define "server_2" do |server_2|
    server_2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.name = "server_2"
    end
    server_2.vm.network "private_network", ip: "192.168.33.20"
    server_2.vm.hostname = "server_2"
  end


  # server_3 VM
  config.vm.define "server_3" do |server_3|
    server_3.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.name = "server_3"
    end
    server_3.vm.network "private_network", ip: "192.168.33.21"
    server_3.vm.hostname = "server_3"
  end
end
