Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  # automation VM
  config.vm.define "automation" do |automation|
    automation.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "automation"
    end
    automation.vm.network "private_network", ip: "192.168.33.22"
    automation.vm.hostname = "automation"
  end

  # production VM
  config.vm.define "production" do |production|
    production.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.name = "production"
    end
    production.vm.network "private_network", ip: "192.168.33.21"
    production.vm.hostname = "production"
  end
end
